FROM golang:1.25 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o proxy-service ./cmd/proxy-service

FROM gcr.io/distroless/base-debian12
WORKDIR /
COPY --from=builder /app/proxy-service /proxy-service
EXPOSE 9090
USER nonroot:nonroot
ENTRYPOINT ["/proxy-service"]
