FROM golang:1.25 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o net-controller ./cmd/net-controller

FROM gcr.io/distroless/base-debian12
WORKDIR /
COPY --from=builder /app/net-controller /net-controller
EXPOSE 9091
USER root:root
ENTRYPOINT ["/net-controller"]
